import Head from 'next/head'
import React, { useState } from 'react'
import { Inter } from '@next/font/google'
import doctor1 from '../public/doctor-images/8.jpg'
import Navbar from '../components/navbar'
import Doctor from '../components/doctor'
import { FiChevronLeft, FiChevronRight } from "react-icons/fi";
import Image from 'next/image'
const inter = Inter({ subsets: ['latin'] })
import logo from '../public/icpc.png'

import CustomDisclosure from '../components/disclosure'

export default function Home() {
  const doctor = {
    name: "TAPIERO Sidney",
    turnover: "50,846",
    basket: "523",
    hours: "12,200",
    hourlyPay: "200",
    acts: "1,648",
    picture: doctor1,
    data: [3581, 380, 1332, 2251]
  }
  return (
    <>
      <Head>
        <title>Doctor Hub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <main className='flex flex-col justify-start items-center p-4 min-h-full'>
          <span className='p-2 2xl:fixed left-2 w-80 sm:relative'>
            <div className='shadow-sm flex flex-col items-center justify-center space-y-2 p-6 m-2  bg-gray-700 rounded border-2'>
              <div className='flex space-x-2'>
                <h2 className="text-1xl text-white">Nb d&apos;actes total</h2>
              </div>
              <h2 className="text-2xl text-white">44,449</h2>
            </div>
            <div className='shadow-sm flex flex-col items-center justify-center space-y-2 p-6 m-2  bg-gray-700 rounded border-2'>
              <div className='flex space-x-2'>
                <h2 className="text-1xl text-white">Nb de vaccinations total</h2>
              </div>
              <h2 className="text-2xl text-white">6,274</h2>
            </div>
          </span>
          <div className='flex justify-center items-center '>
            <span className='flex border-2 border-gray px-5 py-36 rounded bg-gray-100 hover:bg-gray-200 cursor-pointer'>
              <FiChevronLeft size={20} />
            </span>
            <div className='border-2 border-gray/30 mx-6 p-2'>
              <Doctor name={doctor.name} turnover={doctor.turnover} basket={doctor.basket} hours={doctor.basket} hourlyPay={doctor.hourlyPay} acts={doctor.acts} picture={doctor.picture} data={doctor.data} />
            </div>
            <span className='flex border-2 border-gray px-5 py-36 rounded bg-gray-100 hover:bg-gray-200 cursor-pointer'>
              <FiChevronRight size={20} />
            </span>
          </div>
        </main>
      </main>

    </>
  )
}
