import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import dynamic from 'next/dynamic';
import { Inter } from '@next/font/google'
// import doctor1 from '../public/doctor-images/4.jpg'
import Navbar from '../components/navbar'
import Doctor from '../components/doctor'
import SearchBox from '../components/searchbox'
import { FiChevronLeft, FiChevronRight } from "react-icons/fi";
import Image from 'next/image'
const inter = Inter({ subsets: ['latin'] })
// import logo from '../public/icpc.png'
import data from '../public/data/doctor.json'
import logo from '../public/logo.png'

// import CustomDisclosure from '../components/disclosure'

export default function Home() {
  const MAX_SIZE = 47
  const [doctors, setDoctors] = useState({})
  const [current, setCurrent] = useState({ data: [0, 0, 0, 0] })
  const [picture, setPicture] = useState(null)

  useEffect(() => {
    setDoctors(data)
    console.log(data)
  }, [])

  const doctorInstantiation = (id, picture) => {
    return {
      id: id,
      name: doctors.data[id]['Médecin'] + ' ' + doctors.data[id]['Prénom'],
      turnover: doctors.data[id]['CA'],
      basket: doctors.data[id]['Paniers Moyens'],
      hours: doctors.data[id]['heure'],
      hourlyPay: doctors.data[id]['tauxhoraire'],
      acts: doctors.data[id]['Actes par vacation'],
      picture: picture,
      data: [parseFloat(doctors.data[id]["Nombre d'actes"]), parseFloat(doctors.data[id]['Vacation']), parseFloat(doctors.data[id]['consultation']), parseFloat(doctors.data[id]['examen'])]
    }
  }

  const pictureInstantiation = (id) => {
    return import(`../public/doctor-images/${doctors.data[id]['idmed']}.jpg`)
      .then(picture => picture)
      .catch((error) => {
        console.warn('current picture was not found, referred to default')
        return import(`../public/doctor-images/0.jpg`)
          .then(picture => picture)
      })
  }

  useEffect(() => {
    if (doctors.data) {
      pictureInstantiation(0)
        .then((picture) => {
          const doctor = doctorInstantiation(0, picture)
          setCurrent(doctor)
        })
    }
    else {
      console.warn('still loading data...')
    }
  }, [doctors])


  const Farward = () => {
    var id = parseFloat(current.id)
    if (id < MAX_SIZE) {
      id++
      pictureInstantiation(id)
        .then((picture) => {
          const doctor = doctorInstantiation(id, picture)
          setCurrent(doctor)
        })
    }
  }


  const Backward = () => {
    var id = parseFloat(current.id)
    if (id > 0) {
      id--
      pictureInstantiation(id)
        .then((picture) => {
          const doctor = doctorInstantiation(id, picture)
          setCurrent(doctor)
        })
    }
  }

  return (
    <>
      <Head>
        <title>ICPC App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <main className='flex flex-col justify-start items-center p-4 min-h-full'>
          <span className='p-2 m-2 2xl:fixed left-2  w-80 sm:relative'>
            {/* <Image src={logo} className='m-6'></Image> */}
            <SearchBox />
            <br className='my-82' />
            <div className='shadow-sm flex flex-col items-center justify-center space-y-2 p-6 m-2 bg-icpc rounded border-2'>
              <div className='flex space-x-2'>
                <h2 className="text-1xl text-white">Nb d&apos;actes total</h2>
              </div>
              <h2 className="text-2xl text-white">44,449</h2>
            </div>
            <div className='shadow-sm flex flex-col items-center justify-center space-y-2 p-6 m-2  bg-icpc rounded border-2'>
              <div className='flex space-x-2'>
                <h2 className="text-1xl text-white">Nb de vacation total</h2>
              </div>
              <h2 className="text-2xl text-white">6,274</h2>
            </div>
          </span>
          <div className='flex justify-center items-center '>
            <span className='flex border-2 border-gray px-5 py-12 rounded bg-icpc text-white  hover:bg-icpc/10 hover:text-black cursor-pointer transition-all' onClick={() => Backward()}>
              <FiChevronLeft size={20} />
            </span>
            <div className='border-2 border-gray/30 mx-6 p-2'>
              <Doctor name={current.name} turnover={current.turnover} basket={current.basket} hours={current.basket} hourlyPay={current.hourlyPay} acts={current.acts} picture={current.picture} data={current.data} />
            </div>
            <span className='flex border-2 border-gray px-5 py-12 rounded  bg-icpc text-white  hover:bg-icpc/10 hover:text-black cursor-pointer transition-all' onClick={() => Farward()}>
              <FiChevronRight size={20} />
            </span>
          </div>
        </main>
      </main>

    </>
  )
}
